apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: shopsphere-dev
type: Opaque
stringData:
  POSTGRES_USER: shopsphere
  POSTGRES_PASSWORD: shopsphere123
  POSTGRES_DB: shopsphere
